// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_api.proto

package ru.bagrusss.demo;

public interface LoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.Login)
    com.google.protobuf.MessageOrBuilder {
}
