// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realm.proto

package ru.bagrusss.demo;

public interface OperationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.OperationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1 [(.demo.java_field_options) = { ... }</code>
   */
  boolean hasId();
  /**
   * <code>required string id = 1 [(.demo.java_field_options) = { ... }</code>
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1 [(.demo.java_field_options) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated string items = 2;</code>
   */
  java.util.List<java.lang.String>
      getItemsList();
  /**
   * <code>repeated string items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated string items = 2;</code>
   */
  java.lang.String getItems(int index);
  /**
   * <code>repeated string items = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemsBytes(int index);
}
