// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options.proto

package ru.bagrusss.demo;

public final class Options {
  private Options() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(ru.bagrusss.demo.Options.javaMessageOptions);
    registry.add(ru.bagrusss.demo.Options.javaEnumOptions);
    registry.add(ru.bagrusss.demo.Options.javaFileOptions);
    registry.add(ru.bagrusss.demo.Options.javaFieldOptions);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JavaMessageOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.JavaMessageOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    boolean hasGenerateRealmObject();
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    boolean getGenerateRealmObject();

    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    boolean hasAdditionalClassName();
    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    java.lang.String getAdditionalClassName();
    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getAdditionalClassNameBytes();
  }
  /**
   * Protobuf type {@code demo.JavaMessageOptions}
   */
  public  static final class JavaMessageOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.JavaMessageOptions)
      JavaMessageOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JavaMessageOptions.newBuilder() to construct.
    private JavaMessageOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JavaMessageOptions() {
      generateRealmObject_ = false;
      additionalClassName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JavaMessageOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              generateRealmObject_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              additionalClassName_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaMessageOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaMessageOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.Options.JavaMessageOptions.class, ru.bagrusss.demo.Options.JavaMessageOptions.Builder.class);
    }

    private int bitField0_;
    public static final int GENERATE_REALM_OBJECT_FIELD_NUMBER = 1;
    private boolean generateRealmObject_;
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    public boolean hasGenerateRealmObject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    public boolean getGenerateRealmObject() {
      return generateRealmObject_;
    }

    public static final int ADDITIONAL_CLASS_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object additionalClassName_;
    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    public boolean hasAdditionalClassName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    public java.lang.String getAdditionalClassName() {
      java.lang.Object ref = additionalClassName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          additionalClassName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string additional_class_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionalClassNameBytes() {
      java.lang.Object ref = additionalClassName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalClassName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, generateRealmObject_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, additionalClassName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, generateRealmObject_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, additionalClassName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.bagrusss.demo.Options.JavaMessageOptions)) {
        return super.equals(obj);
      }
      ru.bagrusss.demo.Options.JavaMessageOptions other = (ru.bagrusss.demo.Options.JavaMessageOptions) obj;

      boolean result = true;
      result = result && (hasGenerateRealmObject() == other.hasGenerateRealmObject());
      if (hasGenerateRealmObject()) {
        result = result && (getGenerateRealmObject()
            == other.getGenerateRealmObject());
      }
      result = result && (hasAdditionalClassName() == other.hasAdditionalClassName());
      if (hasAdditionalClassName()) {
        result = result && getAdditionalClassName()
            .equals(other.getAdditionalClassName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGenerateRealmObject()) {
        hash = (37 * hash) + GENERATE_REALM_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGenerateRealmObject());
      }
      if (hasAdditionalClassName()) {
        hash = (37 * hash) + ADDITIONAL_CLASS_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getAdditionalClassName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaMessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.bagrusss.demo.Options.JavaMessageOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.JavaMessageOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.JavaMessageOptions)
        ru.bagrusss.demo.Options.JavaMessageOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaMessageOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaMessageOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.bagrusss.demo.Options.JavaMessageOptions.class, ru.bagrusss.demo.Options.JavaMessageOptions.Builder.class);
      }

      // Construct using ru.bagrusss.demo.Options.JavaMessageOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        generateRealmObject_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        additionalClassName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaMessageOptions_descriptor;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaMessageOptions getDefaultInstanceForType() {
        return ru.bagrusss.demo.Options.JavaMessageOptions.getDefaultInstance();
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaMessageOptions build() {
        ru.bagrusss.demo.Options.JavaMessageOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaMessageOptions buildPartial() {
        ru.bagrusss.demo.Options.JavaMessageOptions result = new ru.bagrusss.demo.Options.JavaMessageOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.generateRealmObject_ = generateRealmObject_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.additionalClassName_ = additionalClassName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.bagrusss.demo.Options.JavaMessageOptions) {
          return mergeFrom((ru.bagrusss.demo.Options.JavaMessageOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.bagrusss.demo.Options.JavaMessageOptions other) {
        if (other == ru.bagrusss.demo.Options.JavaMessageOptions.getDefaultInstance()) return this;
        if (other.hasGenerateRealmObject()) {
          setGenerateRealmObject(other.getGenerateRealmObject());
        }
        if (other.hasAdditionalClassName()) {
          bitField0_ |= 0x00000002;
          additionalClassName_ = other.additionalClassName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.bagrusss.demo.Options.JavaMessageOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.bagrusss.demo.Options.JavaMessageOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean generateRealmObject_ ;
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public boolean hasGenerateRealmObject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public boolean getGenerateRealmObject() {
        return generateRealmObject_;
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public Builder setGenerateRealmObject(boolean value) {
        bitField0_ |= 0x00000001;
        generateRealmObject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public Builder clearGenerateRealmObject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        generateRealmObject_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object additionalClassName_ = "";
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public boolean hasAdditionalClassName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public java.lang.String getAdditionalClassName() {
        java.lang.Object ref = additionalClassName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            additionalClassName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAdditionalClassNameBytes() {
        java.lang.Object ref = additionalClassName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          additionalClassName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public Builder setAdditionalClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        additionalClassName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public Builder clearAdditionalClassName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        additionalClassName_ = getDefaultInstance().getAdditionalClassName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string additional_class_name = 2;</code>
       */
      public Builder setAdditionalClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        additionalClassName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.JavaMessageOptions)
    }

    // @@protoc_insertion_point(class_scope:demo.JavaMessageOptions)
    private static final ru.bagrusss.demo.Options.JavaMessageOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.bagrusss.demo.Options.JavaMessageOptions();
    }

    public static ru.bagrusss.demo.Options.JavaMessageOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JavaMessageOptions>
        PARSER = new com.google.protobuf.AbstractParser<JavaMessageOptions>() {
      @java.lang.Override
      public JavaMessageOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JavaMessageOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JavaMessageOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaMessageOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.bagrusss.demo.Options.JavaMessageOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JavaEnumOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.JavaEnumOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    boolean hasGenerateRealmObject();
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    boolean getGenerateRealmObject();
  }
  /**
   * Protobuf type {@code demo.JavaEnumOptions}
   */
  public  static final class JavaEnumOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.JavaEnumOptions)
      JavaEnumOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JavaEnumOptions.newBuilder() to construct.
    private JavaEnumOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JavaEnumOptions() {
      generateRealmObject_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JavaEnumOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              generateRealmObject_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaEnumOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaEnumOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.Options.JavaEnumOptions.class, ru.bagrusss.demo.Options.JavaEnumOptions.Builder.class);
    }

    private int bitField0_;
    public static final int GENERATE_REALM_OBJECT_FIELD_NUMBER = 1;
    private boolean generateRealmObject_;
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    public boolean hasGenerateRealmObject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool generate_realm_object = 1 [default = false];</code>
     */
    public boolean getGenerateRealmObject() {
      return generateRealmObject_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, generateRealmObject_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, generateRealmObject_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.bagrusss.demo.Options.JavaEnumOptions)) {
        return super.equals(obj);
      }
      ru.bagrusss.demo.Options.JavaEnumOptions other = (ru.bagrusss.demo.Options.JavaEnumOptions) obj;

      boolean result = true;
      result = result && (hasGenerateRealmObject() == other.hasGenerateRealmObject());
      if (hasGenerateRealmObject()) {
        result = result && (getGenerateRealmObject()
            == other.getGenerateRealmObject());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGenerateRealmObject()) {
        hash = (37 * hash) + GENERATE_REALM_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGenerateRealmObject());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaEnumOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.bagrusss.demo.Options.JavaEnumOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.JavaEnumOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.JavaEnumOptions)
        ru.bagrusss.demo.Options.JavaEnumOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaEnumOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaEnumOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.bagrusss.demo.Options.JavaEnumOptions.class, ru.bagrusss.demo.Options.JavaEnumOptions.Builder.class);
      }

      // Construct using ru.bagrusss.demo.Options.JavaEnumOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        generateRealmObject_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaEnumOptions_descriptor;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaEnumOptions getDefaultInstanceForType() {
        return ru.bagrusss.demo.Options.JavaEnumOptions.getDefaultInstance();
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaEnumOptions build() {
        ru.bagrusss.demo.Options.JavaEnumOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaEnumOptions buildPartial() {
        ru.bagrusss.demo.Options.JavaEnumOptions result = new ru.bagrusss.demo.Options.JavaEnumOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.generateRealmObject_ = generateRealmObject_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.bagrusss.demo.Options.JavaEnumOptions) {
          return mergeFrom((ru.bagrusss.demo.Options.JavaEnumOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.bagrusss.demo.Options.JavaEnumOptions other) {
        if (other == ru.bagrusss.demo.Options.JavaEnumOptions.getDefaultInstance()) return this;
        if (other.hasGenerateRealmObject()) {
          setGenerateRealmObject(other.getGenerateRealmObject());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.bagrusss.demo.Options.JavaEnumOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.bagrusss.demo.Options.JavaEnumOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean generateRealmObject_ ;
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public boolean hasGenerateRealmObject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public boolean getGenerateRealmObject() {
        return generateRealmObject_;
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public Builder setGenerateRealmObject(boolean value) {
        bitField0_ |= 0x00000001;
        generateRealmObject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool generate_realm_object = 1 [default = false];</code>
       */
      public Builder clearGenerateRealmObject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        generateRealmObject_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.JavaEnumOptions)
    }

    // @@protoc_insertion_point(class_scope:demo.JavaEnumOptions)
    private static final ru.bagrusss.demo.Options.JavaEnumOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.bagrusss.demo.Options.JavaEnumOptions();
    }

    public static ru.bagrusss.demo.Options.JavaEnumOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JavaEnumOptions>
        PARSER = new com.google.protobuf.AbstractParser<JavaEnumOptions>() {
      @java.lang.Override
      public JavaEnumOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JavaEnumOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JavaEnumOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaEnumOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.bagrusss.demo.Options.JavaEnumOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JavaFileOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.JavaFileOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string class_prefix = 1;</code>
     */
    boolean hasClassPrefix();
    /**
     * <code>optional string class_prefix = 1;</code>
     */
    java.lang.String getClassPrefix();
    /**
     * <code>optional string class_prefix = 1;</code>
     */
    com.google.protobuf.ByteString
        getClassPrefixBytes();

    /**
     * <code>optional bool compile_for_framework = 2 [default = true];</code>
     */
    boolean hasCompileForFramework();
    /**
     * <code>optional bool compile_for_framework = 2 [default = true];</code>
     */
    boolean getCompileForFramework();

    /**
     * <code>optional bool generate_realm_models = 3 [default = false];</code>
     */
    boolean hasGenerateRealmModels();
    /**
     * <code>optional bool generate_realm_models = 3 [default = false];</code>
     */
    boolean getGenerateRealmModels();
  }
  /**
   * Protobuf type {@code demo.JavaFileOptions}
   */
  public  static final class JavaFileOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.JavaFileOptions)
      JavaFileOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JavaFileOptions.newBuilder() to construct.
    private JavaFileOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JavaFileOptions() {
      classPrefix_ = "";
      compileForFramework_ = true;
      generateRealmModels_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JavaFileOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              classPrefix_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              compileForFramework_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              generateRealmModels_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaFileOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaFileOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.Options.JavaFileOptions.class, ru.bagrusss.demo.Options.JavaFileOptions.Builder.class);
    }

    private int bitField0_;
    public static final int CLASS_PREFIX_FIELD_NUMBER = 1;
    private volatile java.lang.Object classPrefix_;
    /**
     * <code>optional string class_prefix = 1;</code>
     */
    public boolean hasClassPrefix() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string class_prefix = 1;</code>
     */
    public java.lang.String getClassPrefix() {
      java.lang.Object ref = classPrefix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          classPrefix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string class_prefix = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClassPrefixBytes() {
      java.lang.Object ref = classPrefix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPILE_FOR_FRAMEWORK_FIELD_NUMBER = 2;
    private boolean compileForFramework_;
    /**
     * <code>optional bool compile_for_framework = 2 [default = true];</code>
     */
    public boolean hasCompileForFramework() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool compile_for_framework = 2 [default = true];</code>
     */
    public boolean getCompileForFramework() {
      return compileForFramework_;
    }

    public static final int GENERATE_REALM_MODELS_FIELD_NUMBER = 3;
    private boolean generateRealmModels_;
    /**
     * <code>optional bool generate_realm_models = 3 [default = false];</code>
     */
    public boolean hasGenerateRealmModels() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool generate_realm_models = 3 [default = false];</code>
     */
    public boolean getGenerateRealmModels() {
      return generateRealmModels_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, classPrefix_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, compileForFramework_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, generateRealmModels_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, classPrefix_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, compileForFramework_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, generateRealmModels_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.bagrusss.demo.Options.JavaFileOptions)) {
        return super.equals(obj);
      }
      ru.bagrusss.demo.Options.JavaFileOptions other = (ru.bagrusss.demo.Options.JavaFileOptions) obj;

      boolean result = true;
      result = result && (hasClassPrefix() == other.hasClassPrefix());
      if (hasClassPrefix()) {
        result = result && getClassPrefix()
            .equals(other.getClassPrefix());
      }
      result = result && (hasCompileForFramework() == other.hasCompileForFramework());
      if (hasCompileForFramework()) {
        result = result && (getCompileForFramework()
            == other.getCompileForFramework());
      }
      result = result && (hasGenerateRealmModels() == other.hasGenerateRealmModels());
      if (hasGenerateRealmModels()) {
        result = result && (getGenerateRealmModels()
            == other.getGenerateRealmModels());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClassPrefix()) {
        hash = (37 * hash) + CLASS_PREFIX_FIELD_NUMBER;
        hash = (53 * hash) + getClassPrefix().hashCode();
      }
      if (hasCompileForFramework()) {
        hash = (37 * hash) + COMPILE_FOR_FRAMEWORK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getCompileForFramework());
      }
      if (hasGenerateRealmModels()) {
        hash = (37 * hash) + GENERATE_REALM_MODELS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGenerateRealmModels());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFileOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.bagrusss.demo.Options.JavaFileOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.JavaFileOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.JavaFileOptions)
        ru.bagrusss.demo.Options.JavaFileOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFileOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFileOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.bagrusss.demo.Options.JavaFileOptions.class, ru.bagrusss.demo.Options.JavaFileOptions.Builder.class);
      }

      // Construct using ru.bagrusss.demo.Options.JavaFileOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        classPrefix_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        compileForFramework_ = true;
        bitField0_ = (bitField0_ & ~0x00000002);
        generateRealmModels_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFileOptions_descriptor;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFileOptions getDefaultInstanceForType() {
        return ru.bagrusss.demo.Options.JavaFileOptions.getDefaultInstance();
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFileOptions build() {
        ru.bagrusss.demo.Options.JavaFileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFileOptions buildPartial() {
        ru.bagrusss.demo.Options.JavaFileOptions result = new ru.bagrusss.demo.Options.JavaFileOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.classPrefix_ = classPrefix_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.compileForFramework_ = compileForFramework_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.generateRealmModels_ = generateRealmModels_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.bagrusss.demo.Options.JavaFileOptions) {
          return mergeFrom((ru.bagrusss.demo.Options.JavaFileOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.bagrusss.demo.Options.JavaFileOptions other) {
        if (other == ru.bagrusss.demo.Options.JavaFileOptions.getDefaultInstance()) return this;
        if (other.hasClassPrefix()) {
          bitField0_ |= 0x00000001;
          classPrefix_ = other.classPrefix_;
          onChanged();
        }
        if (other.hasCompileForFramework()) {
          setCompileForFramework(other.getCompileForFramework());
        }
        if (other.hasGenerateRealmModels()) {
          setGenerateRealmModels(other.getGenerateRealmModels());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.bagrusss.demo.Options.JavaFileOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.bagrusss.demo.Options.JavaFileOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object classPrefix_ = "";
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public boolean hasClassPrefix() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public java.lang.String getClassPrefix() {
        java.lang.Object ref = classPrefix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            classPrefix_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClassPrefixBytes() {
        java.lang.Object ref = classPrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          classPrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public Builder setClassPrefix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        classPrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public Builder clearClassPrefix() {
        bitField0_ = (bitField0_ & ~0x00000001);
        classPrefix_ = getDefaultInstance().getClassPrefix();
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_prefix = 1;</code>
       */
      public Builder setClassPrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        classPrefix_ = value;
        onChanged();
        return this;
      }

      private boolean compileForFramework_ = true;
      /**
       * <code>optional bool compile_for_framework = 2 [default = true];</code>
       */
      public boolean hasCompileForFramework() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool compile_for_framework = 2 [default = true];</code>
       */
      public boolean getCompileForFramework() {
        return compileForFramework_;
      }
      /**
       * <code>optional bool compile_for_framework = 2 [default = true];</code>
       */
      public Builder setCompileForFramework(boolean value) {
        bitField0_ |= 0x00000002;
        compileForFramework_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool compile_for_framework = 2 [default = true];</code>
       */
      public Builder clearCompileForFramework() {
        bitField0_ = (bitField0_ & ~0x00000002);
        compileForFramework_ = true;
        onChanged();
        return this;
      }

      private boolean generateRealmModels_ ;
      /**
       * <code>optional bool generate_realm_models = 3 [default = false];</code>
       */
      public boolean hasGenerateRealmModels() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool generate_realm_models = 3 [default = false];</code>
       */
      public boolean getGenerateRealmModels() {
        return generateRealmModels_;
      }
      /**
       * <code>optional bool generate_realm_models = 3 [default = false];</code>
       */
      public Builder setGenerateRealmModels(boolean value) {
        bitField0_ |= 0x00000004;
        generateRealmModels_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool generate_realm_models = 3 [default = false];</code>
       */
      public Builder clearGenerateRealmModels() {
        bitField0_ = (bitField0_ & ~0x00000004);
        generateRealmModels_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.JavaFileOptions)
    }

    // @@protoc_insertion_point(class_scope:demo.JavaFileOptions)
    private static final ru.bagrusss.demo.Options.JavaFileOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.bagrusss.demo.Options.JavaFileOptions();
    }

    public static ru.bagrusss.demo.Options.JavaFileOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JavaFileOptions>
        PARSER = new com.google.protobuf.AbstractParser<JavaFileOptions>() {
      @java.lang.Override
      public JavaFileOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JavaFileOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JavaFileOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaFileOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.bagrusss.demo.Options.JavaFileOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JavaFieldOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.JavaFieldOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool realm_indexed = 1 [default = false];</code>
     */
    boolean hasRealmIndexed();
    /**
     * <code>optional bool realm_indexed = 1 [default = false];</code>
     */
    boolean getRealmIndexed();

    /**
     * <code>optional bool realm_primary_key = 2 [default = false];</code>
     */
    boolean hasRealmPrimaryKey();
    /**
     * <code>optional bool realm_primary_key = 2 [default = false];</code>
     */
    boolean getRealmPrimaryKey();
  }
  /**
   * Protobuf type {@code demo.JavaFieldOptions}
   */
  public  static final class JavaFieldOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.JavaFieldOptions)
      JavaFieldOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JavaFieldOptions.newBuilder() to construct.
    private JavaFieldOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JavaFieldOptions() {
      realmIndexed_ = false;
      realmPrimaryKey_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JavaFieldOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              realmIndexed_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              realmPrimaryKey_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaFieldOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.Options.internal_static_demo_JavaFieldOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.Options.JavaFieldOptions.class, ru.bagrusss.demo.Options.JavaFieldOptions.Builder.class);
    }

    private int bitField0_;
    public static final int REALM_INDEXED_FIELD_NUMBER = 1;
    private boolean realmIndexed_;
    /**
     * <code>optional bool realm_indexed = 1 [default = false];</code>
     */
    public boolean hasRealmIndexed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool realm_indexed = 1 [default = false];</code>
     */
    public boolean getRealmIndexed() {
      return realmIndexed_;
    }

    public static final int REALM_PRIMARY_KEY_FIELD_NUMBER = 2;
    private boolean realmPrimaryKey_;
    /**
     * <code>optional bool realm_primary_key = 2 [default = false];</code>
     */
    public boolean hasRealmPrimaryKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool realm_primary_key = 2 [default = false];</code>
     */
    public boolean getRealmPrimaryKey() {
      return realmPrimaryKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, realmIndexed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, realmPrimaryKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, realmIndexed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, realmPrimaryKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.bagrusss.demo.Options.JavaFieldOptions)) {
        return super.equals(obj);
      }
      ru.bagrusss.demo.Options.JavaFieldOptions other = (ru.bagrusss.demo.Options.JavaFieldOptions) obj;

      boolean result = true;
      result = result && (hasRealmIndexed() == other.hasRealmIndexed());
      if (hasRealmIndexed()) {
        result = result && (getRealmIndexed()
            == other.getRealmIndexed());
      }
      result = result && (hasRealmPrimaryKey() == other.hasRealmPrimaryKey());
      if (hasRealmPrimaryKey()) {
        result = result && (getRealmPrimaryKey()
            == other.getRealmPrimaryKey());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRealmIndexed()) {
        hash = (37 * hash) + REALM_INDEXED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRealmIndexed());
      }
      if (hasRealmPrimaryKey()) {
        hash = (37 * hash) + REALM_PRIMARY_KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRealmPrimaryKey());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.Options.JavaFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.bagrusss.demo.Options.JavaFieldOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.JavaFieldOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.JavaFieldOptions)
        ru.bagrusss.demo.Options.JavaFieldOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFieldOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFieldOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.bagrusss.demo.Options.JavaFieldOptions.class, ru.bagrusss.demo.Options.JavaFieldOptions.Builder.class);
      }

      // Construct using ru.bagrusss.demo.Options.JavaFieldOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        realmIndexed_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        realmPrimaryKey_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.bagrusss.demo.Options.internal_static_demo_JavaFieldOptions_descriptor;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFieldOptions getDefaultInstanceForType() {
        return ru.bagrusss.demo.Options.JavaFieldOptions.getDefaultInstance();
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFieldOptions build() {
        ru.bagrusss.demo.Options.JavaFieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.bagrusss.demo.Options.JavaFieldOptions buildPartial() {
        ru.bagrusss.demo.Options.JavaFieldOptions result = new ru.bagrusss.demo.Options.JavaFieldOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.realmIndexed_ = realmIndexed_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.realmPrimaryKey_ = realmPrimaryKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.bagrusss.demo.Options.JavaFieldOptions) {
          return mergeFrom((ru.bagrusss.demo.Options.JavaFieldOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.bagrusss.demo.Options.JavaFieldOptions other) {
        if (other == ru.bagrusss.demo.Options.JavaFieldOptions.getDefaultInstance()) return this;
        if (other.hasRealmIndexed()) {
          setRealmIndexed(other.getRealmIndexed());
        }
        if (other.hasRealmPrimaryKey()) {
          setRealmPrimaryKey(other.getRealmPrimaryKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.bagrusss.demo.Options.JavaFieldOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.bagrusss.demo.Options.JavaFieldOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean realmIndexed_ ;
      /**
       * <code>optional bool realm_indexed = 1 [default = false];</code>
       */
      public boolean hasRealmIndexed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool realm_indexed = 1 [default = false];</code>
       */
      public boolean getRealmIndexed() {
        return realmIndexed_;
      }
      /**
       * <code>optional bool realm_indexed = 1 [default = false];</code>
       */
      public Builder setRealmIndexed(boolean value) {
        bitField0_ |= 0x00000001;
        realmIndexed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool realm_indexed = 1 [default = false];</code>
       */
      public Builder clearRealmIndexed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        realmIndexed_ = false;
        onChanged();
        return this;
      }

      private boolean realmPrimaryKey_ ;
      /**
       * <code>optional bool realm_primary_key = 2 [default = false];</code>
       */
      public boolean hasRealmPrimaryKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool realm_primary_key = 2 [default = false];</code>
       */
      public boolean getRealmPrimaryKey() {
        return realmPrimaryKey_;
      }
      /**
       * <code>optional bool realm_primary_key = 2 [default = false];</code>
       */
      public Builder setRealmPrimaryKey(boolean value) {
        bitField0_ |= 0x00000002;
        realmPrimaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool realm_primary_key = 2 [default = false];</code>
       */
      public Builder clearRealmPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        realmPrimaryKey_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.JavaFieldOptions)
    }

    // @@protoc_insertion_point(class_scope:demo.JavaFieldOptions)
    private static final ru.bagrusss.demo.Options.JavaFieldOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.bagrusss.demo.Options.JavaFieldOptions();
    }

    public static ru.bagrusss.demo.Options.JavaFieldOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JavaFieldOptions>
        PARSER = new com.google.protobuf.AbstractParser<JavaFieldOptions>() {
      @java.lang.Override
      public JavaFieldOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JavaFieldOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JavaFieldOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaFieldOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.bagrusss.demo.Options.JavaFieldOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int JAVA_MESSAGE_OPTIONS_FIELD_NUMBER = 5100985;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.MessageOptions,
      ru.bagrusss.demo.Options.JavaMessageOptions> javaMessageOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ru.bagrusss.demo.Options.JavaMessageOptions.class,
        ru.bagrusss.demo.Options.JavaMessageOptions.getDefaultInstance());
  public static final int JAVA_ENUM_OPTIONS_FIELD_NUMBER = 5100984;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.EnumOptions,
      ru.bagrusss.demo.Options.JavaEnumOptions> javaEnumOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ru.bagrusss.demo.Options.JavaEnumOptions.class,
        ru.bagrusss.demo.Options.JavaEnumOptions.getDefaultInstance());
  public static final int JAVA_FILE_OPTIONS_FIELD_NUMBER = 5100987;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.FileOptions,
      ru.bagrusss.demo.Options.JavaFileOptions> javaFileOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ru.bagrusss.demo.Options.JavaFileOptions.class,
        ru.bagrusss.demo.Options.JavaFileOptions.getDefaultInstance());
  public static final int JAVA_FIELD_OPTIONS_FIELD_NUMBER = 5100986;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.FieldOptions,
      ru.bagrusss.demo.Options.JavaFieldOptions> javaFieldOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ru.bagrusss.demo.Options.JavaFieldOptions.class,
        ru.bagrusss.demo.Options.JavaFieldOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_JavaMessageOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_JavaMessageOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_JavaEnumOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_JavaEnumOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_JavaFileOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_JavaFileOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_JavaFieldOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_JavaFieldOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\roptions.proto\022\004demo\032 google/protobuf/d" +
      "escriptor.proto\"Y\n\022JavaMessageOptions\022$\n" +
      "\025generate_realm_object\030\001 \001(\010:\005false\022\035\n\025a" +
      "dditional_class_name\030\002 \001(\t\"7\n\017JavaEnumOp" +
      "tions\022$\n\025generate_realm_object\030\001 \001(\010:\005fa" +
      "lse\"r\n\017JavaFileOptions\022\024\n\014class_prefix\030\001" +
      " \001(\t\022#\n\025compile_for_framework\030\002 \001(\010:\004tru" +
      "e\022$\n\025generate_realm_models\030\003 \001(\010:\005false\"" +
      "R\n\020JavaFieldOptions\022\034\n\rrealm_indexed\030\001 \001" +
      "(\010:\005false\022 \n\021realm_primary_key\030\002 \001(\010:\005fa" +
      "lse:Z\n\024java_message_options\022\037.google.pro" +
      "tobuf.MessageOptions\030\271\253\267\002 \001(\0132\030.demo.Jav" +
      "aMessageOptions:Q\n\021java_enum_options\022\034.g" +
      "oogle.protobuf.EnumOptions\030\270\253\267\002 \001(\0132\025.de" +
      "mo.JavaEnumOptions:Q\n\021java_file_options\022" +
      "\034.google.protobuf.FileOptions\030\273\253\267\002 \001(\0132\025" +
      ".demo.JavaFileOptions:T\n\022java_field_opti" +
      "ons\022\035.google.protobuf.FieldOptions\030\272\253\267\002 " +
      "\001(\0132\026.demo.JavaFieldOptionsB\031\n\020ru.bagrus" +
      "ss.demo\332\333\272\023\002\020\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_demo_JavaMessageOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_JavaMessageOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_JavaMessageOptions_descriptor,
        new java.lang.String[] { "GenerateRealmObject", "AdditionalClassName", });
    internal_static_demo_JavaEnumOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_JavaEnumOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_JavaEnumOptions_descriptor,
        new java.lang.String[] { "GenerateRealmObject", });
    internal_static_demo_JavaFileOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_JavaFileOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_JavaFileOptions_descriptor,
        new java.lang.String[] { "ClassPrefix", "CompileForFramework", "GenerateRealmModels", });
    internal_static_demo_JavaFieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_demo_JavaFieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_JavaFieldOptions_descriptor,
        new java.lang.String[] { "RealmIndexed", "RealmPrimaryKey", });
    javaMessageOptions.internalInit(descriptor.getExtensions().get(0));
    javaEnumOptions.internalInit(descriptor.getExtensions().get(1));
    javaFileOptions.internalInit(descriptor.getExtensions().get(2));
    javaFieldOptions.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(ru.bagrusss.demo.Options.javaFileOptions);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
