// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realm.proto

package ru.bagrusss.demo;

public final class Realm {
  private Realm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_OperationList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_OperationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013realm.proto\022\004demo\032\roptions.proto\"C\n\rOp" +
      "erationList\022\032\n\002id\030\001 \002(\tB\016\322\333\272\023\002\020\001\322\333\272\023\002\010\001\022" +
      "\r\n\005items\030\002 \003(\t:\007\312\333\272\023\002\010\001B\024\n\020ru.bagrusss.d" +
      "emoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.bagrusss.demo.Options.getDescriptor(),
        }, assigner);
    internal_static_demo_OperationList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_OperationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_OperationList_descriptor,
        new java.lang.String[] { "Id", "Items", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(ru.bagrusss.demo.Options.javaFieldOptions);
    registry.add(ru.bagrusss.demo.Options.javaMessageOptions);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    ru.bagrusss.demo.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
