// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package ru.bagrusss.demo;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_User_Phone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_User_Phone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Contacts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Contacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004demo\"\301\001\n\004User\022\014\n\004name\030\001 \002(" +
      "\t\022\n\n\002id\030\002 \002(\003\022\r\n\005email\030\003 \001(\t\022 \n\006phones\030\004" +
      " \003(\0132\020.demo.User.Phone\032A\n\005Phone\022\016\n\006numbe" +
      "r\030\001 \002(\t\022(\n\004type\030\002 \001(\0162\024.demo.User.PhoneT" +
      "ype:\004HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HO" +
      "ME\020\001\022\010\n\004WORK\020\002\"&\n\010Contacts\022\032\n\006people\030\001 \003" +
      "(\0132\n.demo.UserB\024\n\020ru.bagrusss.demoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_User_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_demo_User_Phone_descriptor =
      internal_static_demo_User_descriptor.getNestedTypes().get(0);
    internal_static_demo_User_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_User_Phone_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_demo_Contacts_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Contacts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Contacts_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
