// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collections.proto

package ru.bagrusss.demo.proto;

public final class CollectionsOuterClass {
  private CollectionsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Collections_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Collections_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Collections_UsersMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Collections_UsersMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021collections.proto\022\004demo\032\nuser.proto\"\216\001" +
      "\n\013Collections\022\017\n\007strings\030\001 \003(\t\0221\n\010usersM" +
      "ap\030\002 \003(\0132\037.demo.Collections.UsersMapEntr" +
      "y\032;\n\rUsersMapEntry\022\013\n\003key\030\001 \001(\t\022\031\n\005value" +
      "\030\002 \001(\0132\n.demo.User:\0028\001B\032\n\026ru.bagrusss.de" +
      "mo.protoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.bagrusss.demo.proto.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_demo_Collections_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Collections_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Collections_descriptor,
        new java.lang.String[] { "Strings", "UsersMap", });
    internal_static_demo_Collections_UsersMapEntry_descriptor =
      internal_static_demo_Collections_descriptor.getNestedTypes().get(0);
    internal_static_demo_Collections_UsersMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Collections_UsersMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    ru.bagrusss.demo.proto.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
