// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package ru.bagrusss.demo.proto;

public interface Contacts3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.Contacts3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .demo.User3 people = 1;</code>
   */
  java.util.List<ru.bagrusss.demo.proto.User3> 
      getPeopleList();
  /**
   * <code>repeated .demo.User3 people = 1;</code>
   */
  ru.bagrusss.demo.proto.User3 getPeople(int index);
  /**
   * <code>repeated .demo.User3 people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .demo.User3 people = 1;</code>
   */
  java.util.List<? extends ru.bagrusss.demo.proto.User3OrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .demo.User3 people = 1;</code>
   */
  ru.bagrusss.demo.proto.User3OrBuilder getPeopleOrBuilder(
      int index);
}
