// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_api.proto

package ru.bagrusss.demo.proto;

public final class ServerApi {
  private ServerApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Login_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Login_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Login_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Login_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Logout_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Logout_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Logout_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Logout_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Logout_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Logout_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020server_api.proto\022\004demo\032\nuser.proto\"\232\001\n" +
      "\005Login\032X\n\007Request\022\024\n\004path\030\001 \002(\t:\006/login\022" +
      "\024\n\006method\030\002 \002(\t:\004post\022\013\n\003pin\030\003 \001(\t\022\024\n\014to" +
      "uchIdToken\030\004 \001(\t\0327\n\010Response\022\021\n\tauthToke" +
      "n\030\001 \002(\t\022\030\n\004user\030\002 \002(\0132\n.demo.User\"N\n\006Log" +
      "out\0328\n\007Request\022\025\n\004path\030\001 \002(\t:\007/logout\022\026\n" +
      "\006method\030\002 \002(\t:\006delete\032\n\n\010ResponseB\032\n\026ru." +
      "bagrusss.demo.protoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.bagrusss.demo.proto.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_demo_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Login_descriptor,
        new java.lang.String[] { });
    internal_static_demo_Login_Request_descriptor =
      internal_static_demo_Login_descriptor.getNestedTypes().get(0);
    internal_static_demo_Login_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Login_Request_descriptor,
        new java.lang.String[] { "Path", "Method", "Pin", "TouchIdToken", });
    internal_static_demo_Login_Response_descriptor =
      internal_static_demo_Login_descriptor.getNestedTypes().get(1);
    internal_static_demo_Login_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Login_Response_descriptor,
        new java.lang.String[] { "AuthToken", "User", });
    internal_static_demo_Logout_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Logout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Logout_descriptor,
        new java.lang.String[] { });
    internal_static_demo_Logout_Request_descriptor =
      internal_static_demo_Logout_descriptor.getNestedTypes().get(0);
    internal_static_demo_Logout_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Logout_Request_descriptor,
        new java.lang.String[] { "Path", "Method", });
    internal_static_demo_Logout_Response_descriptor =
      internal_static_demo_Logout_descriptor.getNestedTypes().get(1);
    internal_static_demo_Logout_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Logout_Response_descriptor,
        new java.lang.String[] { });
    ru.bagrusss.demo.proto.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
