// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package ru.bagrusss.demo.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int64 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>required int64 id = 2;</code>
   */
  long getId();

  /**
   * <code>optional string email = 3;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .demo.User.Phone phones = 4;</code>
   */
  java.util.List<ru.bagrusss.demo.proto.User.Phone> 
      getPhonesList();
  /**
   * <code>repeated .demo.User.Phone phones = 4;</code>
   */
  ru.bagrusss.demo.proto.User.Phone getPhones(int index);
  /**
   * <code>repeated .demo.User.Phone phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .demo.User.Phone phones = 4;</code>
   */
  java.util.List<? extends ru.bagrusss.demo.proto.User.PhoneOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .demo.User.Phone phones = 4;</code>
   */
  ru.bagrusss.demo.proto.User.PhoneOrBuilder getPhonesOrBuilder(
      int index);
}
