// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package ru.bagrusss.demo.proto;

/**
 * Protobuf type {@code demo.User3}
 */
public  final class User3 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:demo.User3)
    User3OrBuilder {
private static final long serialVersionUID = 0L;
  // Use User3.newBuilder() to construct.
  private User3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User3() {
    name_ = "";
    id_ = 0L;
    email_ = "";
    phones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User3(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            id_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              phones_ = new java.util.ArrayList<ru.bagrusss.demo.proto.User3.Phone>();
              mutable_bitField0_ |= 0x00000008;
            }
            phones_.add(
                input.readMessage(ru.bagrusss.demo.proto.User3.Phone.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        phones_ = java.util.Collections.unmodifiableList(phones_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.bagrusss.demo.proto.User3.class, ru.bagrusss.demo.proto.User3.Builder.class);
  }

  /**
   * Protobuf enum {@code demo.User3.PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOBILE = 0;</code>
     */
    MOBILE(0),
    /**
     * <code>HOME = 1;</code>
     */
    HOME(1),
    /**
     * <code>WORK = 2;</code>
     */
    WORK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOBILE = 0;</code>
     */
    public static final int MOBILE_VALUE = 0;
    /**
     * <code>HOME = 1;</code>
     */
    public static final int HOME_VALUE = 1;
    /**
     * <code>WORK = 2;</code>
     */
    public static final int WORK_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return MOBILE;
        case 1: return HOME;
        case 2: return WORK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ru.bagrusss.demo.proto.User3.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:demo.User3.PhoneType)
  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.User3.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.demo.User3.PhoneType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.demo.User3.PhoneType type = 2;</code>
     */
    ru.bagrusss.demo.proto.User3.PhoneType getType();
  }
  /**
   * Protobuf type {@code demo.User3.Phone}
   */
  public  static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.User3.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Phone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.proto.User3.Phone.class, ru.bagrusss.demo.proto.User3.Phone.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 1;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.demo.User3.PhoneType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.demo.User3.PhoneType type = 2;</code>
     */
    public ru.bagrusss.demo.proto.User3.PhoneType getType() {
      @SuppressWarnings("deprecation")
      ru.bagrusss.demo.proto.User3.PhoneType result = ru.bagrusss.demo.proto.User3.PhoneType.valueOf(type_);
      return result == null ? ru.bagrusss.demo.proto.User3.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != ru.bagrusss.demo.proto.User3.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != ru.bagrusss.demo.proto.User3.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.bagrusss.demo.proto.User3.Phone)) {
        return super.equals(obj);
      }
      ru.bagrusss.demo.proto.User3.Phone other = (ru.bagrusss.demo.proto.User3.Phone) obj;

      boolean result = true;
      result = result && getNumber()
          .equals(other.getNumber());
      result = result && type_ == other.type_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.bagrusss.demo.proto.User3.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.bagrusss.demo.proto.User3.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.User3.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.User3.Phone)
        ru.bagrusss.demo.proto.User3.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.bagrusss.demo.proto.User3.Phone.class, ru.bagrusss.demo.proto.User3.Phone.Builder.class);
      }

      // Construct using ru.bagrusss.demo.proto.User3.Phone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_Phone_descriptor;
      }

      @java.lang.Override
      public ru.bagrusss.demo.proto.User3.Phone getDefaultInstanceForType() {
        return ru.bagrusss.demo.proto.User3.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public ru.bagrusss.demo.proto.User3.Phone build() {
        ru.bagrusss.demo.proto.User3.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.bagrusss.demo.proto.User3.Phone buildPartial() {
        ru.bagrusss.demo.proto.User3.Phone result = new ru.bagrusss.demo.proto.User3.Phone(this);
        result.number_ = number_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.bagrusss.demo.proto.User3.Phone) {
          return mergeFrom((ru.bagrusss.demo.proto.User3.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.bagrusss.demo.proto.User3.Phone other) {
        if (other == ru.bagrusss.demo.proto.User3.Phone.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.bagrusss.demo.proto.User3.Phone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.bagrusss.demo.proto.User3.Phone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.demo.User3.PhoneType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.demo.User3.PhoneType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.demo.User3.PhoneType type = 2;</code>
       */
      public ru.bagrusss.demo.proto.User3.PhoneType getType() {
        @SuppressWarnings("deprecation")
        ru.bagrusss.demo.proto.User3.PhoneType result = ru.bagrusss.demo.proto.User3.PhoneType.valueOf(type_);
        return result == null ? ru.bagrusss.demo.proto.User3.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.demo.User3.PhoneType type = 2;</code>
       */
      public Builder setType(ru.bagrusss.demo.proto.User3.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.demo.User3.PhoneType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.User3.Phone)
    }

    // @@protoc_insertion_point(class_scope:demo.User3.Phone)
    private static final ru.bagrusss.demo.proto.User3.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.bagrusss.demo.proto.User3.Phone();
    }

    public static ru.bagrusss.demo.proto.User3.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Phone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.bagrusss.demo.proto.User3.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_;
  /**
   * <code>int64 id = 2;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 3;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONES_FIELD_NUMBER = 4;
  private java.util.List<ru.bagrusss.demo.proto.User3.Phone> phones_;
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  public java.util.List<ru.bagrusss.demo.proto.User3.Phone> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  public java.util.List<? extends ru.bagrusss.demo.proto.User3.PhoneOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  public ru.bagrusss.demo.proto.User3.Phone getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  public ru.bagrusss.demo.proto.User3.PhoneOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (id_ != 0L) {
      output.writeInt64(2, id_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(4, phones_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, phones_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.bagrusss.demo.proto.User3)) {
      return super.equals(obj);
    }
    ru.bagrusss.demo.proto.User3 other = (ru.bagrusss.demo.proto.User3) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getId()
        == other.getId());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && getPhonesList()
        .equals(other.getPhonesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + getPhonesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.bagrusss.demo.proto.User3 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.bagrusss.demo.proto.User3 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.bagrusss.demo.proto.User3 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.bagrusss.demo.proto.User3 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.bagrusss.demo.proto.User3 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code demo.User3}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:demo.User3)
      ru.bagrusss.demo.proto.User3OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.bagrusss.demo.proto.User3.class, ru.bagrusss.demo.proto.User3.Builder.class);
    }

    // Construct using ru.bagrusss.demo.proto.User3.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhonesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      id_ = 0L;

      email_ = "";

      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.bagrusss.demo.proto.User3OuterClass.internal_static_demo_User3_descriptor;
    }

    @java.lang.Override
    public ru.bagrusss.demo.proto.User3 getDefaultInstanceForType() {
      return ru.bagrusss.demo.proto.User3.getDefaultInstance();
    }

    @java.lang.Override
    public ru.bagrusss.demo.proto.User3 build() {
      ru.bagrusss.demo.proto.User3 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.bagrusss.demo.proto.User3 buildPartial() {
      ru.bagrusss.demo.proto.User3 result = new ru.bagrusss.demo.proto.User3(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.id_ = id_;
      result.email_ = email_;
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.bagrusss.demo.proto.User3) {
        return mergeFrom((ru.bagrusss.demo.proto.User3)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.bagrusss.demo.proto.User3 other) {
      if (other == ru.bagrusss.demo.proto.User3.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.bagrusss.demo.proto.User3 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.bagrusss.demo.proto.User3) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 2;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.util.List<ru.bagrusss.demo.proto.User3.Phone> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        phones_ = new java.util.ArrayList<ru.bagrusss.demo.proto.User3.Phone>(phones_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.bagrusss.demo.proto.User3.Phone, ru.bagrusss.demo.proto.User3.Phone.Builder, ru.bagrusss.demo.proto.User3.PhoneOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public java.util.List<ru.bagrusss.demo.proto.User3.Phone> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public ru.bagrusss.demo.proto.User3.Phone getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder setPhones(
        int index, ru.bagrusss.demo.proto.User3.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder setPhones(
        int index, ru.bagrusss.demo.proto.User3.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder addPhones(ru.bagrusss.demo.proto.User3.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder addPhones(
        int index, ru.bagrusss.demo.proto.User3.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder addPhones(
        ru.bagrusss.demo.proto.User3.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder addPhones(
        int index, ru.bagrusss.demo.proto.User3.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends ru.bagrusss.demo.proto.User3.Phone> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public ru.bagrusss.demo.proto.User3.Phone.Builder getPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public ru.bagrusss.demo.proto.User3.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public java.util.List<? extends ru.bagrusss.demo.proto.User3.PhoneOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public ru.bagrusss.demo.proto.User3.Phone.Builder addPhonesBuilder() {
      return getPhonesFieldBuilder().addBuilder(
          ru.bagrusss.demo.proto.User3.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public ru.bagrusss.demo.proto.User3.Phone.Builder addPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().addBuilder(
          index, ru.bagrusss.demo.proto.User3.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .demo.User3.Phone phones = 4;</code>
     */
    public java.util.List<ru.bagrusss.demo.proto.User3.Phone.Builder> 
         getPhonesBuilderList() {
      return getPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.bagrusss.demo.proto.User3.Phone, ru.bagrusss.demo.proto.User3.Phone.Builder, ru.bagrusss.demo.proto.User3.PhoneOrBuilder> 
        getPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.bagrusss.demo.proto.User3.Phone, ru.bagrusss.demo.proto.User3.Phone.Builder, ru.bagrusss.demo.proto.User3.PhoneOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:demo.User3)
  }

  // @@protoc_insertion_point(class_scope:demo.User3)
  private static final ru.bagrusss.demo.proto.User3 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.bagrusss.demo.proto.User3();
  }

  public static ru.bagrusss.demo.proto.User3 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User3>
      PARSER = new com.google.protobuf.AbstractParser<User3>() {
    @java.lang.Override
    public User3 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User3(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User3> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User3> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.bagrusss.demo.proto.User3 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

