// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package ru.bagrusss.demo.proto;

public final class User3OuterClass {
  private User3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_User3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_User3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_User3_Phone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_User3_Phone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Contacts3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Contacts3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013user3.proto\022\004demo\"\276\001\n\005User3\022\014\n\004name\030\001 " +
      "\001(\t\022\n\n\002id\030\002 \001(\003\022\r\n\005email\030\003 \001(\t\022!\n\006phones" +
      "\030\004 \003(\0132\021.demo.User3.Phone\032<\n\005Phone\022\016\n\006nu" +
      "mber\030\001 \001(\t\022#\n\004type\030\002 \001(\0162\025.demo.User3.Ph" +
      "oneType\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME" +
      "\020\001\022\010\n\004WORK\020\002\"(\n\tContacts3\022\033\n\006people\030\001 \003(" +
      "\0132\013.demo.User3B\032\n\026ru.bagrusss.demo.proto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_User3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_User3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_User3_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_demo_User3_Phone_descriptor =
      internal_static_demo_User3_descriptor.getNestedTypes().get(0);
    internal_static_demo_User3_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_User3_Phone_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_demo_Contacts3_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Contacts3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Contacts3_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
