// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user3.proto

package ru.bagrusss.demo.proto;

public interface User3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.User3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 id = 2;</code>
   */
  long getId();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  java.util.List<ru.bagrusss.demo.proto.User3.Phone> 
      getPhonesList();
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  ru.bagrusss.demo.proto.User3.Phone getPhones(int index);
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  java.util.List<? extends ru.bagrusss.demo.proto.User3.PhoneOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .demo.User3.Phone phones = 4;</code>
   */
  ru.bagrusss.demo.proto.User3.PhoneOrBuilder getPhonesOrBuilder(
      int index);
}
